/* 
This panel is for demonstration purpose, it is an external plugin, auto generated by Datav.

The origin plugin files is in https://github.com/data-observe/datav/tree/main/ui/external-plugins
*/

// This demo datasource is just a copy of Promtheus datasource
import { DatasourcePluginComponents } from "types/plugins/plugin";
import DemoDatasourceEditor from "./DatasourceEditor";
import DemoVariableEditor from "./VariableEditor";
import DemoQueryEditor from "./QueryEditor";
import { queryAlerts, queryVariableValues, replaceQueryWithVariables, runQuery, testDatasource } from "./query_runner";

const demoComponents: DatasourcePluginComponents = {
    datasourceEditor: DemoDatasourceEditor,
    variableEditor:DemoVariableEditor,
    queryEditor: DemoQueryEditor,
    
    // defined in query_runner.ts
    runQuery: runQuery,
    testDatasource: testDatasource,
    replaceQueryWithVariables: replaceQueryWithVariables,
    queryVariableValues: queryVariableValues,
    queryAlerts: queryAlerts,
}

export default  demoComponents