export const showcase = [
  {
    name: 'OpenAI / ChatGPT',
    slug: 'openai',
    thumbnail: require('@/img/showcase/thumbnails/openai.com.png').default,
    video: require('@/videos/showcase/openai.com.mp4').default,
    description: 'Marketing website & chat interface',
  },
  {
    name: 'Lemon Squeezy',
    slug: 'lemon-squeezy',
    thumbnail: require('@/img/showcase/thumbnails/app.lemonsqueezy.com.png').default,
    video: require('@/videos/showcase/app.lemonsqueezy.com.mp4').default,
    description: 'SaaS application',
  },
  {
    name: 'Shopify',
    slug: 'shopify',
    thumbnail: require('@/img/showcase/thumbnails/shopify.com.png').default,
    video: require('@/videos/showcase/shopify.com.mp4').default,
    description: 'Ecommerce platform website',
  },
  {
    name: 'Wealthfront',
    slug: 'wealthfront',
    thumbnail: require('@/img/showcase/thumbnails/wealthfront.com.png').default,
    video: require('@/videos/showcase/wealthfront.com.mp4').default,
    description: 'Fintech marketing website',
  },
  {
    name: 'Netflix Global Top 10',
    slug: 'netflix',
    thumbnail: require('@/img/showcase/thumbnails/top10.netflix.com.png').default,
    video: require('@/videos/showcase/top10.netflix.com.mp4').default,
    description: 'Microsite',
  },
  {
    name: 'Loom',
    slug: 'loom',
    thumbnail: require('@/img/showcase/thumbnails/loom.com.png').default,
    video: require('@/videos/showcase/loom.com.mp4').default,
    description: 'SaaS marketing website',
  },
  {
    name: 'The Verge',
    slug: 'the-verge',
    thumbnail: require('@/img/showcase/thumbnails/theverge.com.png').default,
    video: require('@/videos/showcase/theverge.com.mp4').default,
    description: 'News website',
  },
  {
    name: 'Laracon Online',
    slug: 'laracon',
    thumbnail: require('@/img/showcase/thumbnails/laracon.net.png').default,
    video: require('@/videos/showcase/laracon.net.mp4').default,
    description: 'Conference website',
  },
  {
    name: 'Turbo',
    slug: 'turbo',
    thumbnail: require('@/img/showcase/thumbnails/turbo.build.png').default,
    video: require('@/videos/showcase/turbo.build.mp4').default,
    description: 'Developer tool website',
  },
  {
    name: 'candycode',
    slug: 'candycode',
    thumbnail: require('@/img/showcase/thumbnails/candycode.com.png').default,
    video: require('@/videos/showcase/candycode.com.mp4').default,
    description: 'Agency website',
  },
  {
    name: 'Column',
    slug: 'column',
    thumbnail: require('@/img/showcase/thumbnails/column.com.png').default,
    video: require('@/videos/showcase/column.com.mp4').default,
    description: 'Fintech marketing website',
  },
  {
    name: 'Wander',
    slug: 'wander',
    thumbnail: require('@/img/showcase/thumbnails/wander.com.png').default,
    video: require('@/videos/showcase/wander.com.mp4').default,
    description: 'Vacation rental website',
  },
  {
    name: 'New York Times Events',
    slug: 'nytimes',
    thumbnail: require('@/img/showcase/thumbnails/nytimes.com.png').default,
    video: require('@/videos/showcase/nytimes.com.mp4').default,
    description: 'News website',
  },
  {
    name: 'GitHub Next',
    slug: 'github',
    thumbnail: require('@/img/showcase/thumbnails/githubnext.com.png').default,
    video: require('@/videos/showcase/githubnext.com.mp4').default,
    description: 'Research website',
  },
  {
    name: 'PlanetScale',
    slug: 'planetscale',
    thumbnail: require('@/img/showcase/thumbnails/planetscale.com.png').default,
    video: require('@/videos/showcase/planetscale.com.mp4').default,
    description: 'SaaS marketing website',
  },
  {
    name: 'Algolia Docs',
    slug: 'algolia',
    thumbnail: require('@/img/showcase/thumbnails/algolia.com.png').default,
    video: require('@/videos/showcase/algolia.com.mp4').default,
    description: 'Documentation website',
  },
  {
    name: 'MrBeast Feastables',
    slug: 'feastables',
    thumbnail: require('@/img/showcase/thumbnails/feastables.com.png').default,
    video: require('@/videos/showcase/feastables.com.mp4').default,
    description: 'Direct-to-consumer store',
  },
  {
    name: 'NASA Jet Propulsion Laboratory',
    slug: 'nasa',
    thumbnail: require('@/img/showcase/thumbnails/jpl.nasa.gov.png').default,
    video: require('@/videos/showcase/jpl.nasa.gov.mp4').default,
    description: 'Space laboratory website',
  },
  {
    name: 'Salient',
    slug: 'salient',
    thumbnail: require('@/img/showcase/thumbnails/salient.tailwindui.com.png').default,
    video: require('@/videos/showcase/salient.tailwindui.com.mp4').default,
    description: 'SaaS marketing website',
    isTemplate: true,
  },
  {
    name: 'Mashable',
    slug: 'mashable',
    thumbnail: require('@/img/showcase/thumbnails/mashable.com.png').default,
    video: require('@/videos/showcase/mashable.com.mp4').default,
    description: 'News website',
  },
  {
    name: 'Microsoft .NET',
    slug: 'dotnet',
    thumbnail: require('@/img/showcase/thumbnails/dotnet.microsoft.com.png').default,
    video: require('@/videos/showcase/dotnet.microsoft.com.mp4').default,
    description: 'Software framework website',
  },
  {
    name: 'Spotlight',
    slug: 'spotlight',
    thumbnail: require('@/img/showcase/thumbnails/spotlight.tailwindui.com.png').default,
    video: require('@/videos/showcase/spotlight.tailwindui.com.mp4').default,
    description: 'Personal website',
    isTemplate: true,
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/spotlight.tailwindui.com-dark.png').default,
      video: require('@/videos/showcase/spotlight.tailwindui.com-dark.mp4').default,
    },
  },
  {
    name: 'Clearbit',
    slug: 'clearbit',
    thumbnail: require('@/img/showcase/thumbnails/clearbit.com.png').default,
    video: require('@/videos/showcase/clearbit.com.mp4').default,
    description: 'SaaS marketing website',
  },
  {
    name: 'Dizzie',
    slug: 'dizzie',
    thumbnail: require('@/img/showcase/thumbnails/getdizzie.com.png').default,
    video: require('@/videos/showcase/getdizzie.com.mp4').default,
    description: 'E-commerce store',
  },
  {
    name: 'Google I/O 2022',
    slug: 'google-io-2022',
    thumbnail: require('@/img/showcase/thumbnails/io.google.png').default,
    video: require('@/videos/showcase/io.google.mp4').default,
    description: 'Conference website',
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/io.google-dark.png').default,
      video: require('@/videos/showcase/io.google-dark.mp4').default,
    },
  },
  {
    name: 'Keynote',
    slug: 'keynote',
    thumbnail: require('@/img/showcase/thumbnails/keynote.tailwindui.com.png').default,
    video: require('@/videos/showcase/keynote.tailwindui.com.mp4').default,
    description: 'Conference website',
    isTemplate: true,
  },
  {
    name: 'KeepGrading',
    slug: 'keepgrading',
    thumbnail: require('@/img/showcase/thumbnails/keepgrading.com.png').default,
    video: require('@/videos/showcase/keepgrading.com.mp4').default,
    description: 'Agency website',
  },
  {
    name: 'Transmit',
    slug: 'transmit',
    thumbnail: require('@/img/showcase/thumbnails/transmit.tailwindui.com.png').default,
    video: require('@/videos/showcase/transmit.tailwindui.com.mp4').default,
    description: 'Podcast website',
    isTemplate: true,
  },
  {
    name: 'Poolsuite Grand Leisure',
    slug: 'grand-leisure',
    thumbnail: require('@/img/showcase/thumbnails/grandleisure.org.png').default,
    video: require('@/videos/showcase/grandleisure.org.mp4').default,
    description: 'NFT marketing website',
  },
  {
    name: 'Pocket',
    slug: 'pocket',
    thumbnail: require('@/img/showcase/thumbnails/pocket.tailwindui.com.png').default,
    video: require('@/videos/showcase/pocket.tailwindui.com.mp4').default,
    description: 'Mobile app marketing website',
    isTemplate: true,
  },
  {
    name: 'Modern Treasury',
    slug: 'modern-treasury',
    thumbnail: require('@/img/showcase/thumbnails/moderntreasury.com.png').default,
    video: require('@/videos/showcase/moderntreasury.com.mp4').default,
    description: 'Fintech marketing website',
  },
  {
    name: 'National Park Foundation',
    slug: 'national-park-foundation',
    thumbnail: require('@/img/showcase/thumbnails/nationalparks.org.png').default,
    video: require('@/videos/showcase/nationalparks.org.mp4').default,
    description: 'Nonprofit website',
  },
  {
    name: 'Syntax',
    slug: 'syntax',
    thumbnail: require('@/img/showcase/thumbnails/syntax.tailwindui.com.png').default,
    video: require('@/videos/showcase/syntax.tailwindui.com.mp4').default,
    description: 'Documentation website',
    isTemplate: true,
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/syntax.tailwindui.com-dark.png').default,
      video: require('@/videos/showcase/syntax.tailwindui.com-dark.mp4').default,
    },
  },
  {
    name: 'SavvyCal',
    slug: 'savvycal',
    thumbnail: require('@/img/showcase/thumbnails/savvycal.com.png').default,
    video: require('@/videos/showcase/savvycal.com.mp4').default,
    description: 'SaaS application',
  },
  {
    name: 'Opal',
    slug: 'opal',
    thumbnail: require('@/img/showcase/thumbnails/opalcamera.com.png').default,
    video: require('@/videos/showcase/opalcamera.com.mp4').default,
    description: 'Product marketing website',
  },
  {
    name: 'Coinbase NFT',
    slug: 'coinbase',
    thumbnail: require('@/img/showcase/thumbnails/nft.coinbase.com.png').default,
    video: require('@/videos/showcase/nft.coinbase.com.mp4').default,
    description: 'Online marketplace',
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/nft.coinbase.com-dark.png').default,
      video: require('@/videos/showcase/nft.coinbase.com-dark.mp4').default,
    },
  },
  {
    name: 'Primer',
    slug: 'primer',
    thumbnail: require('@/img/showcase/thumbnails/primer.tailwindui.com.png').default,
    video: require('@/videos/showcase/primer.tailwindui.com.mp4').default,
    description: 'Info product website',
    isTemplate: true,
  },
  {
    name: 'Der Spiegel',
    slug: 'spiegel',
    thumbnail: require('@/img/showcase/thumbnails/spiegel.de.png').default,
    video: require('@/videos/showcase/spiegel.de.mp4').default,
    description: 'News website',
    dark: {
      thumbnail: require('@/img/showcase/thumbnails/spiegel.de-dark.png').default,
      video: require('@/videos/showcase/spiegel.de-dark.mp4').default,
    },
  },
]
