/* 
This panel is for demonstration purpose, it is an external plugin, auto generated by Datav.

The origin plugin files is in https://github.com/data-observe/datav/tree/main/ui/external-plugins
*/

// This demo datasource is just a copy of Promtheus datasource
import { DatasourcePluginComponents } from "types/plugin";
import DatasourceEditor from "./DatasourceEditor";
import VariableEditor from "./VariableEditor";
import QueryEditor from "./QueryEditor";
import getDocs from "./docs";
import { DatasourceTypePrometheus } from "./types"
import icon from './icon.svg'
import { testPrometheusDatasource, queryPromethuesVariableValues, query_prometheus_alerts, replacePrometheusQueryWithVariables, runPrometheusQuery } from "./query_runner";

const components: DatasourcePluginComponents = {
    datasourceEditor: DatasourceEditor,
    variableEditor:VariableEditor,
    queryEditor: QueryEditor,
    getDocs: getDocs, //docs showing in panel editor

    // defined in query_runner.ts
    runQuery: runPrometheusQuery,
    testDatasource: testPrometheusDatasource,
    replaceQueryWithVariables: replacePrometheusQueryWithVariables,
    queryVariableValues: queryPromethuesVariableValues,
    queryAlerts: query_prometheus_alerts,

    settings:{
        type: DatasourceTypePrometheus,
        icon,
    }
}

export default  components