
// DON'T modify this file, it is automatically generated by Datav external plugin system
import { PanelType } from "types/dashboard"
import { DatasourcePluginComponents, PanelPluginComponents } from "types/plugins/plugin"

import graphPanel from './panel/graph'
import alertPanel from './panel/alert'
import barPanel from './panel/bar'
import barGaugePanel from './panel/barGauge'
import echartsPanel from './panel/echarts'
import gaugePanel from './panel/gauge'
import geomapPanel from './panel/geomap'
import logPanel from './panel/log'
import nodeGraphPanel from './panel/nodeGraph'
import piePanel from './panel/pie'
import statPanel from './panel/stat'
import tablePanel from './panel/table'
import textPanel from './panel/text'
import tracePanel from './panel/trace'


export const builtinPanelPlugins: Record<string,PanelPluginComponents> = {
	[PanelType.Graph]: graphPanel,
    [PanelType.Alert]: alertPanel,
    [PanelType.Bar]: barPanel,
    [PanelType.BarGauge]: barGaugePanel,
    [PanelType.Echarts]: echartsPanel,
    [PanelType.Gauge]: gaugePanel,
    [PanelType.GeoMap]: geomapPanel,
    [PanelType.Log]: logPanel,
    [PanelType.NodeGraph]: nodeGraphPanel,
    [PanelType.Pie]: piePanel,
    [PanelType.Stat]: statPanel,
    [PanelType.Table]: tablePanel,
    [PanelType.Text]: textPanel,
    [PanelType.Trace]: tracePanel,

}

export const builtinDatasourcePlugins: Record<string,DatasourcePluginComponents> = {
}