
// DON'T modify this file, it is automatically generated by Datav external plugin system
import { PanelType } from "types/dashboard"
import { DatasourcePluginComponents, PanelPluginComponents } from "types/plugins/plugin"

import graphPanel from './panel/graph'
import alertPanel from './panel/alert'
import barPanel from './panel/bar'
import barGaugePanel from './panel/barGauge'
import echartsPanel from './panel/echarts'
import gaugePanel from './panel/gauge'
import geomapPanel from './panel/geomap'
import logPanel from './panel/log'
import nodeGraphPanel from './panel/nodeGraph'

export const builtinPanelPlugins: Record<string,PanelPluginComponents> = {
	[PanelType.Graph]: graphPanel,
    [PanelType.Alert]: alertPanel,
    [PanelType.Bar]: barPanel,
    [PanelType.BarGauge]: barGaugePanel,
    [PanelType.Echarts]: echartsPanel,
    [PanelType.Gauge]: gaugePanel,
    [PanelType.GeoMap]: geomapPanel,
    [PanelType.Log]: logPanel,
    [PanelType.NodeGraph]: nodeGraphPanel,
}

export const builtinDatasourcePlugins: Record<string,DatasourcePluginComponents> = {
}