
// DON'T modify this file, it is automatically generated by Datav external plugin system
import { PanelType } from "types/dashboard"
import { DatasourcePluginComponents, PanelPluginComponents } from "types/plugins/plugin"
import graphComponents from './panel/graph'
import alertComponents from './panel/alert'
import barComponents from './panel/bar'
import barGaugeComponents from './panel/barGauge'

export const builtinPanelPlugins: Record<string,PanelPluginComponents> = {
	[PanelType.Graph]: graphComponents,
    [PanelType.Alert]: alertComponents,
    [PanelType.Bar]: barComponents,
    [PanelType.BarGauge]: barGaugeComponents,
}

export const builtinDatasourcePlugins: Record<string,DatasourcePluginComponents> = {
}