/* 
This panel is for demonstration purpose, it is an external plugin, auto generated by observex.

The origin plugin files is in https://github.com/data-observe/observex/tree/main/ui/external-plugins
*/

// This demo datasource is just a copy of Promtheus datasource
import { DatasourcePluginComponents } from "types/plugin";
import DatasourceEditor from "./DatasourceEditor";
import VariableEditor from "./VariableEditor";
import QueryEditor from "./QueryEditor";
import { DatasourceTypeobservex } from "./types"
import { checkAndTestDatasource, queryobservexVariableValues, query_http_alerts, replaceobservexQueryWithVariables, runQuery } from "./query_runner";
import { $config } from "src/data/configs/config";


const getDisabled = () => {
    return  !$config.get().observability.enable
}

const components: DatasourcePluginComponents = {
    datasourceEditor: DatasourceEditor,
    variableEditor:VariableEditor,
    queryEditor: QueryEditor,

    // defined in query_runner.ts
    runQuery: runQuery,
    testDatasource: checkAndTestDatasource,
    replaceQueryWithVariables: replaceobservexQueryWithVariables,
    queryVariableValues: queryobservexVariableValues,
    
    queryAlerts: query_http_alerts,

    settings:{
        type: DatasourceTypeobservex,
        icon: "/logo.png",
        disabled: getDisabled
    }
}

export default  components
