/* 
This panel is for demonstration purpose, it is an external plugin, auto generated by Datav.

The origin plugin files is in https://github.com/data-observe/datav/tree/main/ui/external-plugins
*/

// This demo datasource is just a copy of Promtheus datasource
import { DatasourcePluginComponents } from "types/plugin";
import DatasourceEditor from "./DatasourceEditor";
import VariableEditor from "./VariableEditor";
import QueryEditor from "./QueryEditor";
import { DatasourceTypeHttp } from "./types"
import { checkAndTestHttp, queryHttpVariableValues, query_http_alerts, replaceHttpQueryWithVariables, run_http_query } from "./query_runner";
import { $config } from "src/data/configs/config";


const getDisabled = () => {
    return  !$config.get().observability.enable
}

const components: DatasourcePluginComponents = {
    datasourceEditor: DatasourceEditor,
    variableEditor:VariableEditor,
    queryEditor: QueryEditor,

    // defined in query_runner.ts
    runQuery: run_http_query,
    testDatasource: checkAndTestHttp,
    replaceQueryWithVariables: replaceHttpQueryWithVariables,
    queryVariableValues: queryHttpVariableValues,
    
    queryAlerts: query_http_alerts,

    settings:{
        type: DatasourceTypeHttp,
        icon: "/logo.png",
        disabled: getDisabled
    }
}

export default  components
