/*This file is auto generated by datav, changes will not have any effect*/ 
import * as plugin4b0f25be95d59e92180340420f162f81 from 'src/plugins/built-in/panel/dependency-graph/module'; 
import * as plugin7affab7aaa3018479fc24f836a9ade11 from 'src/plugins/built-in/panel/timeseries/module'; 
import * as plugin3e0d2ecce056064524069b105211665f from 'src/plugins/built-in/panel/echarts/module'; 
import * as plugin37e1a9c3ba6042b79266687d13f3c5ff from 'src/plugins/built-in/panel/gauge/module'; 
import * as pluginf59f8b23db35ab96f36a2d0146ef0de8 from 'src/plugins/built-in/panel/info-table/module'; 
import * as pluginc9ac98acc80da970a07ce83ea74d87e2 from 'src/plugins/built-in/panel/jaeger-panel/module'; 
import * as plugin77ddcb5f19832f4145345889013ab3a4 from 'src/plugins/built-in/panel/stat/module'; 
import * as pluginaab9e1de16f38176f86d7a92ba337a8d from 'src/plugins/built-in/panel/table/module'; 
import * as plugin33f5a962944e9a34604b15c82543d95b from 'src/plugins/built-in/panel/alerts-list/module'; 
import * as plugin387dec387138251637f7c5b4d34e6a02 from 'src/plugins/built-in/panel/bargauge/module'; 
import * as plugin1cb251ec0d568de6a929b520c4aed8d1 from 'src/plugins/built-in/panel/text/module'; 
import * as plugin40be4e59b9a2a2b5dffb918c0e86b3d7 from 'src/plugins/built-in/panel/welcome/module'; 
const plugind9c0e52dd15274d51041b489c7cea0ad = async () => await import(/* webpackChunkName: 'plugind9c0e52dd15274d51041b489c7cea0ad' */ 'src/plugins/built-in/datasource/grafana/module'); 
const plugin80791b3ae7002cb88c246876d9faa8f8 = async () => await import(/* webpackChunkName: 'plugin80791b3ae7002cb88c246876d9faa8f8' */ 'src/plugins/built-in/datasource/http/module'); 
const pluginc769d3f4cac9e43c087b71e074737688 = async () => await import(/* webpackChunkName: 'pluginc769d3f4cac9e43c087b71e074737688' */ 'src/plugins/built-in/datasource/jaeger/module'); 
const plugine4f00638b8a10e6994e67af2f832d51c = async () => await import(/* webpackChunkName: 'plugine4f00638b8a10e6994e67af2f832d51c' */ 'src/plugins/built-in/datasource/prometheus/module'); 
const pluginf0d09f6b3c81655fbac6bb78ccbe20ac = async () => await import(/* webpackChunkName: 'pluginf0d09f6b3c81655fbac6bb78ccbe20ac' */ 'src/plugins/built-in/datasource/staticdata/module'); 
export const builtInPlugins = { 
	'src/plugins/built-in/panel/dependency-graph/module': plugin4b0f25be95d59e92180340420f162f81,
	'src/plugins/built-in/panel/timeseries/module': plugin7affab7aaa3018479fc24f836a9ade11,
	'src/plugins/built-in/panel/echarts/module': plugin3e0d2ecce056064524069b105211665f,
	'src/plugins/built-in/panel/gauge/module': plugin37e1a9c3ba6042b79266687d13f3c5ff,
	'src/plugins/built-in/panel/info-table/module': pluginf59f8b23db35ab96f36a2d0146ef0de8,
	'src/plugins/built-in/panel/jaeger-panel/module': pluginc9ac98acc80da970a07ce83ea74d87e2,
	'src/plugins/built-in/panel/stat/module': plugin77ddcb5f19832f4145345889013ab3a4,
	'src/plugins/built-in/panel/table/module': pluginaab9e1de16f38176f86d7a92ba337a8d,
	'src/plugins/built-in/panel/alerts-list/module': plugin33f5a962944e9a34604b15c82543d95b,
	'src/plugins/built-in/panel/bargauge/module': plugin387dec387138251637f7c5b4d34e6a02,
	'src/plugins/built-in/panel/text/module': plugin1cb251ec0d568de6a929b520c4aed8d1,
	'src/plugins/built-in/panel/welcome/module': plugin40be4e59b9a2a2b5dffb918c0e86b3d7,
	'src/plugins/built-in/datasource/grafana/module': plugind9c0e52dd15274d51041b489c7cea0ad,
	'src/plugins/built-in/datasource/http/module': plugin80791b3ae7002cb88c246876d9faa8f8,
	'src/plugins/built-in/datasource/jaeger/module': pluginc769d3f4cac9e43c087b71e074737688,
	'src/plugins/built-in/datasource/prometheus/module': plugine4f00638b8a10e6994e67af2f832d51c,
	'src/plugins/built-in/datasource/staticdata/module': pluginf0d09f6b3c81655fbac6bb78ccbe20ac,
}