/*This file is auto generated by datav, changes will not have any effect*/ 
import * as plugin05531b19bb846b18c09f979eeb429ad3 from 'src/plugins/external/panel/clock/module'; 
export const externalPlugins = { 
	'src/plugins/external/panel/clock/module': plugin05531b19bb846b18c09f979eeb429ad3,
}