/* 
This panel is for demonstration purpose, it is an external plugin, auto generated by xobserve.

The origin plugin files is in https://github.com/xObserve/xobserve/tree/main/ui/external-plugins
*/

// This demo datasource is just a copy of Promtheus datasource
import { DatasourcePluginComponents } from "types/plugin";
import DatasourceEditor from "./DatasourceEditor";
import VariableEditor from "./VariableEdtitor";
import QueryEditor from "./QueryEditor";
import { DatasourceTypeLoki } from "./types"
import icon from './icon.svg'
import { checkAndTestLoki, queryLokiVariableValues, query_loki_alerts, replaceLokiQueryWithVariables, run_loki_query } from "./query_runner";

const components: DatasourcePluginComponents = {
    datasourceEditor: DatasourceEditor,
    variableEditor:VariableEditor,
    queryEditor: QueryEditor,

    // defined in query_runner.ts
    runQuery: run_loki_query,
    testDatasource: checkAndTestLoki,
    replaceQueryWithVariables: replaceLokiQueryWithVariables,
    queryVariableValues: queryLokiVariableValues,
    queryAlerts: query_loki_alerts,

    settings:{
        type: DatasourceTypeLoki,
        icon,
    }
}

export default  components