
// DON'T modify this file, it is automatically generated by Datav external plugin system
import { PanelPluginComponents } from "types/plugins/plugin"

import DemoComponents from "./panel/demo"
export const externalPanelPlugins: Record<string,PanelPluginComponents> = {
	"demo": DemoComponents,
}