
// DON'T modify this file, it is automatically generated by Datav external plugin system
import { DatasourcePluginComponents, PanelPluginComponents } from "types/plugins/plugin"

import DemoComponents from "./panel/demo"
import DatasourceDemoComponents from './datasource/demo'

export const externalPanelPlugins: Record<string,PanelPluginComponents> = {
	"demo": DemoComponents,
}

export const externalDatasourcePlugins: Record<string,DatasourcePluginComponents> = {
	"demo": DatasourceDemoComponents,
}